name: Run Shell Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils xmlstarlet

      - name: Make test scripts executable
        run: chmod +x test/*.sh script/*.sh

      - name: Run tests
        run: ./test/test.sh