name: Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils xmlstarlet

      - name: Start MinIO Server
        run: |
          docker run -d --name minio \
            -p 9000:9000 \
            -e MINIO_ROOT_USER=minioadmin \
            -e MINIO_ROOT_PASSWORD=minioadmin \
            -e MINIO_ACCESS_KEY=minioadmin \
            -e MINIO_SECRET_KEY=minioadmin \
            minio/minio server /data

      - name: Make test scripts executable
        run: chmod +x test/*.sh script/*.sh

      - name: Create test S3 bucket
        env:
          AWS_ACCESS_KEY_ID: minioadmin
          AWS_SECRET_ACCESS_KEY: minioadmin
          AWS_DEFAULT_REGION: eu-west-2
        run: |
          aws --endpoint-url http://localhost:9000 s3 mb s3://test-bucket

      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: minioadmin
          AWS_SECRET_ACCESS_KEY: minioadmin
          AWS_DEFAULT_REGION: eu-west-2
          AWS_ENDPOINT_URL: http://localhost:9000
        run: ./test/test.sh
